"""Embedded, area-agnostic text assets: guides and workspace templates."""
from __future__ import annotations

WRITING_RULES = """# Human-voice writing rules (anti "AI tells")

Write with your own voice. The goal is not to fool a detector (detectors have ~18% false
positives on human text and several universities disabled them); the goal is to write better.
Detectors mostly penalize uniformity, so the first rule is: vary. The rules are language
agnostic; examples are given in English and Spanish.

1. No em dash (-). Use a comma, period, colon, or parentheses.
2. Drop AI filler. EN: "in conclusion", "it's important to note", "delve into", "in the realm
   of". ES: "cabe destacar", "es importante senalar", "en conclusion", "en el vibrante mundo de".
3. No negative parallelism. Avoid "not only ... but also" / "no solo ... sino tambien" and
   "it's not X, it's Y" / "no se trata de X, sino de Y". Assert directly.
4. Break the rule of three. Don't chain triples ("fast, reliable, and scalable"). Vary the count:
   sometimes two items, sometimes four, sometimes none.
5. Vary sentence length (raise burstiness). Mix short, blunt sentences with longer ones. Never a
   paragraph of uniform sentences.
6. Few lists. Prefer running prose; use bullets only when enumerating truly helps.
7. No decorative bold, no heading on every paragraph. Reserve emphasis for key technical terms.
8. Avoid tell-tale vocabulary. EN: "crucial", "pivotal", "robust", "leverage", "underscore",
   "tapestry", "vibrant", "intricate", "meticulous". ES: "fundamental", "crucial", "robusto",
   "fomentar", "subrayar".
9. No chained stock transitions. Don't open consecutive sentences with "Moreover", "Furthermore",
   "Additionally" / "Ademas", "Asimismo", "Por otro lado".
10. No vague attributions. Not "experts agree", "studies show" / "los expertos coinciden",
    "estudios demuestran". Cite author, work, and year.
11. No boilerplate conclusions ("Despite the challenges, X remains relevant").
12. Use "to be" naturally; don't always swap it for "constitutes", "represents", "stands as".
13. Consistent quotes per your style guide; don't mix curly quotes inconsistently.
14. Active voice by default. Limit the passive.
15. No stacked hedging. Don't pile "might", "perhaps", "to some extent" into one sentence.
16. Never invent data or citations. No verifiable source, no claim.
17. No meta-commentary ("as an AI language model", "in this essay we will explore", "I hope this
    helps"). Get straight to the content.
18. One idea per paragraph, in your own voice: concrete examples and, where apt, an argued judgment.
19. Follow your citation style (for example APA 7); citation keys without spaces.
20. Final pass: re-read and fix every "tell" before submitting.

## AI vocabulary to watch (a moving target by model)
delve, tapestry, testament, vibrant, intricate, bolster, pivotal, underscore, leverage, seamless,
showcase, emphasizing, enhance, highlighting. Source: Wikipedia, "Signs of AI writing".
"""

VISUAL_GUIDE = """# Visual design (organizers, slides, infographics)

Graphics have "AI tells" too. Work made by a person does not announce itself or carry template
signatures. Avoid:

1. Meta labels on the graphic ("Concept map", "Infographic", the subject as a top tag). The title
   is the topic, not the document category.
2. Brand or app footers ("Made with...", "Generated by...", a project name). If you must credit a
   source, one sober line, no ornament.
3. Decorative pills that repeat what a card already says. If it adds no information, cut it.
4. Forced symmetry and filler: don't force four identical boxes if the content wants three or five;
   vary lengths and weight.
5. Excess decoration: no watermarks, no decorative emoji, no loud gradients or heavy shadows by
   default. A palette of two to four colors.
6. Coherent, sober icons, not a different flashy icon per element.

Golden rule: it should look made by a person for a specific task, not a stock template.
"""

IMAGES_GUIDE = """# Images: search free sources first, generate with AI only on request

Read the user's intent before adding any image:
- If the user explicitly asks to GENERATE an image or to USE AI ("generate a picture of...",
  "make an AI image"), use an AI image generator.
- Otherwise ("add an image of...", "find a photo", "search a photo of..."), SEARCH free, openly
  licensed sources. Never AI-generate when the user asked to search.

Free sources to search first (all free, most openly licensed):
- Wikimedia Commons (public domain and Creative Commons). MediaSearch:
  https://commons.wikimedia.org/w/index.php?search=<query>&title=Special:MediaSearch&type=image
- Openverse (aggregates hundreds of millions of CC and public-domain images):
  https://openverse.org/search?q=<query>
- Wikipedia article images for a specific named subject (person, place, species, artwork).
- Flickr Commons and open institutional collections (public domain): NASA Images, Smithsonian
  Open Access, PhyloPic for silhouettes.
- Google Images filtered to reusable licenses:
  https://www.google.com/search?tbm=isch&tbs=il:cl&q=<query>
- Free stock photos under their own license (crediting is polite): Unsplash, Pexels, Pixabay.

Licensing and attribution (always):
- Confirm the license allows your use: public domain and CC0 need no permission; CC BY and
  CC BY-SA require credit; check NonCommercial and NoDerivs terms before reusing.
- For CC BY and CC BY-SA, record author, work title, source URL and license, and add the
  attribution in the caption or a credits section.
- Prefer the full-resolution original from the file page, not a thumbnail or a watermarked preview.
- Save the source URL and license with the figure (a caption or the reference library).

AI generation (only when explicitly requested):
- Pollinations is free and needs no key: GET https://image.pollinations.ai/prompt/<text>.
- Any local or API generator the user already has is fine. Disclose that a figure is AI-generated
  when the academic context calls for honesty about the source.

This is guidance; the image_search tool builds the ready queries for a subject, and your host web
tools (search and fetch) pull the actual files.
"""

DOCUMENTS_GUIDE = """# Documents: pick the engine before you build

There is no default engine. ASK the user which one fits the job, and state the trade-off in one
line. Three engines, three jobs:

1. pandoc - the user needs an editable .docx, or automatic APA citations from a .bib file.
   Markdown in, Word or PDF out, with --citeproc resolving the bibliography.
   pandoc essay.md --citeproc --bibliography=references.bib --csl=styles/apa.csl -o essay.docx
2. LaTeX (TinyTeX + apa7) - the work must follow a strict academic template: APA 7 paper, thesis,
   journal submission. Best typography and a real bibliography engine (biblatex), heaviest install.
3. ReportLab (the render_document tool) - the deliverable is a designed PDF: technical report,
   executive summary, dossier, data-driven document. Full control of the page, fine tables, vector
   charts from data, navigable outline, page numbering, two-column sections, watermark.

Decide with the user, not for them:
- "I need to keep editing it in Word" -> pandoc.
- "It has to follow APA to the letter, with references" -> LaTeX (or pandoc + apa.csl).
- "It must look professional and precisely laid out" -> ReportLab.

Know the limit before promising: ReportLab does NOT read BibTeX and does NOT process CSL. It
typesets the reference strings you pass it. When the document needs an automatic bibliography,
build the references with the cite tool (or pandoc) first, then pass them as text.

The render_document spec, format='report':
{ "format": "report", "title", "subtitle", "author", "date", "abstract", "toc": true,
  "watermark", "font": "serif"|"sans", "palette": {"primary","accent","ink","paper"},
  "blocks": [ {"type":"heading","text","level":1|2},
              {"type":"text","text"},
              {"type":"quote","text"},
              {"type":"list","items":[...]},
              {"type":"table","header":[...],"rows":[[...]],"highlight":0,"caption"},
              {"type":"chart","kind":"bar"|"line"|"pie","categories":[...],"values":[...],
               "threshold":50,"label_format":"%d %%","caption"},
              {"type":"columns","count":2},
              {"type":"pagebreak"},
              {"type":"references","items":[...]} ] }

Keep the design sober: the palette takes four colors and the visual rules still apply. A polished
document is not a decorated one.
"""

SLIDES_GUIDE = """# Slides: pick the engine before you build

Two engines, two products. ASK the user which one they want; do not assume.

- Marp - visual and fast, the modern "deck" look. Written in Markdown, themed with CSS, exports
  PDF, PPTX and HTML, has live preview and speaker notes. Choose it when the deck should look
  designed and be edited quickly, or when PPTX or HTML output is required.
- ReportLab (the render_document tool with format='slides') - the technical, precisely typeset
  option. Vector charts from data, fine tables, progress bar, reveal builds, exact positioning,
  and the same palette as the report so a deck and its document match. PDF only.

Ask it plainly: "a visual deck (Marp) or a technical, precisely laid out one (ReportLab)?"

The render_document spec, format='slides':
{ "format": "slides", "title", "progress": true, "font", "palette",
  "slides": [ {"layout":"cover","title","subtitle","lines":[...]},
              {"layout":"bullets","title","reveal":true,
               "items":[{"lead":"Word.","text":"the rest of the point"}]},
              {"layout":"table","title","header":[...],"rows":[[...]],"highlight":0,"note"},
              {"layout":"chart","title","kind":"bar","categories":[...],"values":[...]},
              {"layout":"closing","title","lines":[...]} ] }
Slides are 16:9. 'reveal' emits one page per item, the Beamer way; the cover is not counted in the
slide numbering.

## Marp

Marp turns Markdown into styled, customizable slide decks. Rendering uses a headless Chromium, so
Chrome or Chromium must be available. Before building a deck, ASK the user which output they want
and recommend PDF:
- PDF (recommended): renders identically everywhere, keeps fonts and layout exactly as designed,
  and looks more polished for delivery and submission. Only needs Chromium.
- PPTX default: each slide is embedded as a rendered image (great fidelity, playable and
  annotatable), but the text is NOT editable.
- PPTX editable: needs the experimental --pptx-editable flag, which also requires LibreOffice
  Impress (marp renders with Chromium, then soffice converts it) and can lose styling. Pick it only
  when the user must keep editing the text in PowerPoint. setup.py --all can install LibreOffice; if
  soffice is not on PATH, set SOFFICE_PATH to its binary.

How Marp works:
- One Markdown file. Separate slides with a line of three dashes (---).
- A YAML front matter block sets the deck options:
    ---
    marp: true
    theme: default        # default, gaia, uncover, or a custom CSS theme
    paginate: true
    size: 16:9
    ---
- Per-slide directives go in an HTML comment: <!-- _class: lead --> for a title slide,
  <!-- _backgroundColor: #123 --> to tint one slide.
- Customize with a CSS theme or an inline <style> block; keep it sober (two to four colors, one
  accent), the same anti-AI visual rules as any graphic.
- For images, follow the images guide: search free sources first, generate with AI only if asked.

Export with marp-cli:
- PDF:  marp deck.md --pdf --allow-local-files -o deck.pdf
- PPTX (slides as images): marp deck.md --pptx -o deck.pptx
- PPTX (editable text, experimental, needs LibreOffice): marp deck.md --pptx --pptx-editable -o deck.pptx
- HTML: marp deck.md -o deck.html
- Live preview while writing: marp -p -w deck.md

Content: apply the writing rules (human voice, vary sentence length, no filler). One idea per
slide, a readable title, few words, and let a figure or a short list carry the point.
"""

CITATION_APA = """# APA 7 quick guide

In-text: (Surname, Year) or Surname (Year). Two authors: (Smith & Lee, 2020). Three or more:
(Smith et al., 2020). A direct quote adds the page: (Smith, 2020, p. 12).

Reference list (hanging indent, alphabetical by surname). Italics are marked with *...*:
- Journal article: Author, A. A., & Author, B. B. (Year). Title of the article. *Journal Name*,
  *Volume*(Issue), pages. https://doi.org/xxxxx
- Book: Author, A. A. (Year). *Title of the book* (edition). Publisher.
- Chapter: Author, A. A. (Year). Title of the chapter. In E. Editor (Ed.), *Book title*
  (pp. xx-xx). Publisher.
- Web page: Author, A. A. (Year, Month Day). *Title of the page*. Site Name. URL

Rules: citation keys without spaces (surname2020). Don't cite what you can't verify. For automatic
formatting use a reference manager, or a .bib plus apa.csl with pandoc.
"""

STRUCTURE_GUIDE = """# Academic structure

- Essay or paper: title; abstract (if required); introduction (context, problem, thesis, scope);
  body (one idea per section: claim, cited evidence, your reading); conclusion (answer the thesis,
  no new data, no boilerplate); references.
- IMRaD (empirical work): Introduction, Methods, Results, and Discussion, plus abstract and
  references.
- Argue, don't summarize. Every paragraph should advance a claim, support it with cited evidence,
  and connect back to the thesis.
- Signpost with substance, not with stock transitions; let the logic carry the flow.
- Match length and section weight to the content; don't pad to fill a template.
"""

WORKSPACE_CLAUDE = """# CLAUDE.md - study workspace

A general workspace for academic work in any field. Several areas live under `areas/`; a student
can carry more than one at a time.

## Working rules

1. Language. The workspace structure, folder names, templates, and these conventions are in
   English and stay in English. The *output* follows the user: produce deliverables (essays,
   slides, diagram labels, bibliography notes) and chat in the language the user asks for, or the
   area's language. Default to the user's language and keep spelling and accents correct.
2. Human voice: before delivering any text or graphic, apply `conventions/writing-rules.md`. No em
   dashes, no AI filler, no default lists; vary sentence length. For graphics: no meta labels, no
   brand footers, a palette of two to four colors.
3. Area knowledge: for a task in area X, read and cite from `areas/<X>/knowledge.md`. Never invent
   authors, works, dates, or data. Verify anything marked as unconfirmed before citing it.
4. Citations: APA 7 by default (`conventions/citation-apa.md`); keys without spaces. No verifiable
   source, no claim. The per-area bibliography is `areas/<X>/references.bib`.
5. Memory: at the start of a session read `memory/*.md`. When the user gives a new instruction or
   preference, or starts a task, update the matching file in `memory/` without being asked.
6. Images: search free, openly licensed sources first (Wikimedia Commons, Openverse, Google
   reusable), take the full-resolution original, and record the license and credit. Generate with
   AI only if the user explicitly asks. See `study_guide('images')` and the `image_search` tool.
7. Engine choice: never assume one. Before building a document or a deck, ASK which engine fits.
   Documents: pandoc (editable .docx, automatic APA citations), LaTeX/apa7 (strict academic
   template), or ReportLab via `render_document` (designed, precisely typeset PDF). Slides: Marp
   (visual, Markdown-fast, exports PPTX and HTML) or `render_document` with format='slides'
   (technical, vector charts, reveal builds). With Marp also ask PDF (recommended) or editable
   PPTX. See `study_guide` topics `documents` and `slides`.

## Layout

- `conventions/` - writing rules (anti-AI) and the APA quick guide.
- `styles/` - how to fetch `apa.csl` for pandoc.
- `templates/` - reusable templates (`paper-apa7.tex`, `concept-map-example.json`).
- `memory/` - `profile.md` (the student and their preferences) and `log.md` (ongoing work).
- `areas/<area>/` - `knowledge.md`, `references.bib`, and `library/` (INDEX.md, sources/, notes/).
- `.claude/skills/` - project-scoped skills, loaded when this folder is open in Claude Code.

## Tools

The `study` MCP provides writing_check, burstiness, study_guide, concept_map, cite, image_search,
render_document, toolkit, and the workspace tools (workspace_init, area_add, reference_add,
workspace_status). Call `toolkit` to see what else to install for documents, slides, research,
diagrams, and LaTeX.
"""

KNOWLEDGE_TEMPLATE = """# {area}

Area knowledge base. Curate verified concepts, definitions, and key authors and works here, then
cite them from your work. Mark anything you have not verified and check it before citing it.
"""

INDEX_TEMPLATE = """# Reference library - {area}

| Key | Title | Type | Markdown | Summary |
|---|---|---|---|---|
"""

BIB_HEADER = """% BibTeX references - {area}
"""

MEMORY_PROFILE = """# Profile

Who the student is, field or fields of study, working language, formatting preferences, and
citation style.
"""

MEMORY_LOG = """# Log

Ongoing work, deadlines, and instructions. Update as you go.
"""

APA_CSL_README = """# Citation styles

Place `apa.csl` here to format citations with pandoc.

Download it from the Citation Style Language repository:
https://raw.githubusercontent.com/citation-style-language/styles/master/apa.csl

Then use it: pandoc essay.md --citeproc --bibliography=areas/<area>/references.bib
--csl=styles/apa.csl -o essay.docx
"""

PAPER_APA7_TEX = r"""\documentclass[stu,12pt]{apa7}
\usepackage[american]{babel}
\usepackage{csquotes}
\usepackage[style=apa,backend=biber]{biblatex}
% point this to the bibliography of your area, e.g. ../areas/<area>/references.bib
\addbibresource{references.bib}

\title{Working title}
\shorttitle{Short title}
\author{Author Name}
\affiliation{Institution}
\course{Course}
\professor{Professor}
\duedate{\today}

\abstract{One short paragraph summarizing the work.}

\begin{document}
\maketitle

Body text. Cite a source with \parencite{key2024}. Vary your sentence length and avoid AI tells.

\printbibliography
\end{document}
"""

CONCEPT_MAP_EXAMPLE = """{
  "central": "Central concept",
  "branches": [
    {"label": "First branch", "items": ["Idea", "Idea", {"label": "Detail", "text": "short explanation"}]},
    {"label": "Second branch", "items": ["Idea", "Idea"]}
  ],
  "out": "concept-map.png"
}
"""
